"""Write the deterministic Cantera table consumed by the static browser app."""

from __future__ import annotations

import json
from pathlib import Path

from flame_reference_table import build_browser_reference_data


def main() -> None:
    project_root = Path(__file__).resolve().parents[1]
    destination = project_root / "sodium-lamp" / "reference-data.js"
    payload = json.dumps(
        build_browser_reference_data(),
        indent=2,
        separators=(",", ": "),
    )
    destination.write_text(
        "// Generated by physics_backend/generate_browser_reference.py\n"
        "// Cantera reference data; do not hand-edit.\n"
        f"export const FLAME_REFERENCE_DATA = Object.freeze({payload});\n",
        encoding="utf-8",
    )
    print(destination)


if __name__ == "__main__":
    main()
