// Generated by physics_backend/generate_browser_reference.py
// Cantera reference data; do not hand-edit.
export const FLAME_REFERENCE_DATA = Object.freeze({
  "metadata": {
    "cantera_mechanism": "h2o2.yaml",
    "inlet_temperature_k": 320.0,
    "oxidizer": "O2/N2",
    "transport": "multicomponent + Soret for FreeFlame",
    "equilibrium_scope": "HP thermochemical ceiling",
    "flame_speed_scope": "premixed free-flame comparator, not coaxial-flame closure"
  },
  "equilibrium_axes": {
    "phi": [
      0.5,
      0.75,
      1.0,
      1.25,
      1.5,
      2.0
    ],
    "oxygen_fraction": [
      0.21,
      0.38,
      0.6,
      1.0
    ],
    "pressure_bar": [
      0.5,
      1.4,
      4.0,
      8.0
    ]
  },
  "flame_speed_axes": {
    "phi": [
      0.7,
      1.0,
      1.3
    ],
    "oxygen_fraction": [
      0.21,
      0.38,
      0.6,
      1.0
    ],
    "pressure_bar": [
      0.5,
      1.4,
      4.0,
      8.0
    ]
  },
  "equilibrium": [
    {
      "phi": 0.5,
      "oxygen_fraction": 0.21,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 1662.0898715192484,
      "oxygen_atom_mole_fraction": 1.2993142362149183e-05,
      "hydrogen_atom_mole_fraction": 5.000541698242807e-07,
      "hydroxyl_mole_fraction": 0.0003766730318300484,
      "na_o_o_partial_pump_rate_per_na_s": 0.008014802614156312
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 0.21,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2110.1197540299245,
      "oxygen_atom_mole_fraction": 0.0004476382242814429,
      "hydrogen_atom_mole_fraction": 0.00016014099891390496,
      "hydroxyl_mole_fraction": 0.004517951866276645,
      "na_o_o_partial_pump_rate_per_na_s": 5.902195158505122
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.21,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2373.0834703079463,
      "oxygen_atom_mole_fraction": 0.0008738922116487622,
      "hydrogen_atom_mole_fraction": 0.0026170279331070158,
      "hydroxyl_mole_fraction": 0.00858240010065611,
      "na_o_o_partial_pump_rate_per_na_s": 17.785380154336927
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 0.21,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2347.380885934704,
      "oxygen_atom_mole_fraction": 0.00014114904824861924,
      "hydrogen_atom_mole_fraction": 0.00493940847595178,
      "hydroxyl_mole_fraction": 0.0033536950976064345,
      "na_o_o_partial_pump_rate_per_na_s": 0.4742007359860039
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 0.21,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2251.850135487292,
      "oxygen_atom_mole_fraction": 2.377626764187268e-05,
      "hydrogen_atom_mole_fraction": 0.004085519036208966,
      "hydroxyl_mole_fraction": 0.001234714509386845,
      "na_o_o_partial_pump_rate_per_na_s": 0.014621160240950917
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 0.21,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2072.2255966062553,
      "oxygen_atom_mole_fraction": 1.133556126226589e-06,
      "hydrogen_atom_mole_fraction": 0.0018885740952973525,
      "hydroxyl_mole_fraction": 0.00021471246619898947,
      "na_o_o_partial_pump_rate_per_na_s": 3.924509930041969e-05
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 0.38,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2292.1933213002476,
      "oxygen_atom_mole_fraction": 0.0026584620137953554,
      "hydrogen_atom_mole_fraction": 0.0006220711817399918,
      "hydroxyl_mole_fraction": 0.01381041927536163,
      "na_o_o_partial_pump_rate_per_na_s": 176.41352424803787
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 0.38,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2613.873246166702,
      "oxygen_atom_mole_fraction": 0.009360652626188529,
      "hydrogen_atom_mole_fraction": 0.008365327810638043,
      "hydroxyl_mole_fraction": 0.036262791294622544,
      "na_o_o_partial_pump_rate_per_na_s": 1681.9638361006641
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.38,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2727.5116785327345,
      "oxygen_atom_mole_fraction": 0.008823654598870011,
      "hydrogen_atom_mole_fraction": 0.022693217273820936,
      "hydroxyl_mole_fraction": 0.03920032954851604,
      "na_o_o_partial_pump_rate_per_na_s": 1372.578539692504
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 0.38,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2727.6728005343543,
      "oxygen_atom_mole_fraction": 0.004362891561583445,
      "hydrogen_atom_mole_fraction": 0.03232468462846554,
      "hydroxyl_mole_fraction": 0.027576901701475438,
      "na_o_o_partial_pump_rate_per_na_s": 335.534927606704
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 0.38,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2663.3428287744728,
      "oxygen_atom_mole_fraction": 0.0015223674029486234,
      "hydrogen_atom_mole_fraction": 0.03191903539301979,
      "hydroxyl_mole_fraction": 0.015332076508018752,
      "na_o_o_partial_pump_rate_per_na_s": 42.850732461518966
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 0.38,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2477.363566017362,
      "oxygen_atom_mole_fraction": 0.00014086652438559952,
      "hydrogen_atom_mole_fraction": 0.01899445259745761,
      "hydroxyl_mole_fraction": 0.0038628482271725623,
      "na_o_o_partial_pump_rate_per_na_s": 0.4240426593735317
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 0.6,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2631.140684579845,
      "oxygen_atom_mole_fraction": 0.01746265711283323,
      "hydrogen_atom_mole_fraction": 0.007234310222371542,
      "hydroxyl_mole_fraction": 0.051087268734955955,
      "na_o_o_partial_pump_rate_per_na_s": 5777.047738247356
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 0.6,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2819.18138200273,
      "oxygen_atom_mole_fraction": 0.025821603834103472,
      "hydrogen_atom_mole_fraction": 0.028047578431632605,
      "hydroxyl_mole_fraction": 0.0744084320747577,
      "na_o_o_partial_pump_rate_per_na_s": 11002.562226999637
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.6,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2880.6357940237685,
      "oxygen_atom_mole_fraction": 0.020495668426753454,
      "hydrogen_atom_mole_fraction": 0.050121930141520804,
      "hydroxyl_mole_fraction": 0.07007284217641321,
      "na_o_o_partial_pump_rate_per_na_s": 6639.278875931806
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 0.6,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2873.476707644913,
      "oxygen_atom_mole_fraction": 0.01160146825061094,
      "hydrogen_atom_mole_fraction": 0.0630697584664664,
      "hydroxyl_mole_fraction": 0.052303521225915264,
      "na_o_o_partial_pump_rate_per_na_s": 2137.88329011753
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 0.6,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2821.80664905899,
      "oxygen_atom_mole_fraction": 0.0052048220820714326,
      "hydrogen_atom_mole_fraction": 0.06350512202976447,
      "hydroxyl_mole_fraction": 0.03335825080880113,
      "na_o_o_partial_pump_rate_per_na_s": 446.201180924078
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 0.6,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2656.136172723158,
      "oxygen_atom_mole_fraction": 0.0007394192841460192,
      "hydrogen_atom_mole_fraction": 0.0433471497984782,
      "hydroxyl_mole_fraction": 0.010685102703583044,
      "na_o_o_partial_pump_rate_per_na_s": 10.16375800948039
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 1.0,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2843.9819261216603,
      "oxygen_atom_mole_fraction": 0.048231167766862336,
      "hydrogen_atom_mole_fraction": 0.025497309353339926,
      "hydroxyl_mole_fraction": 0.1068730442963538,
      "na_o_o_partial_pump_rate_per_na_s": 37720.316968488274
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 1.0,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2957.757660081006,
      "oxygen_atom_mole_fraction": 0.04934930511692386,
      "hydrogen_atom_mole_fraction": 0.05818463440490613,
      "hydroxyl_mole_fraction": 0.11995401947048569,
      "na_o_o_partial_pump_rate_per_na_s": 36509.87544439806
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 1.0,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2988.9581469275877,
      "oxygen_atom_mole_fraction": 0.03573970494010968,
      "hydrogen_atom_mole_fraction": 0.08474726282134336,
      "hydroxyl_mole_fraction": 0.10450357614087764,
      "na_o_o_partial_pump_rate_per_na_s": 18751.48647987404
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 1.0,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2972.548158026323,
      "oxygen_atom_mole_fraction": 0.020935573680832306,
      "hydrogen_atom_mole_fraction": 0.0982172551815556,
      "hydroxyl_mole_fraction": 0.07841598099625585,
      "na_o_o_partial_pump_rate_per_na_s": 6505.570336520327
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 1.0,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2923.3692459005256,
      "oxygen_atom_mole_fraction": 0.010417156768035457,
      "hydrogen_atom_mole_fraction": 0.09755194842690103,
      "hydroxyl_mole_fraction": 0.05266124796466001,
      "na_o_o_partial_pump_rate_per_na_s": 1665.3460660819978
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 1.0,
      "pressure_bar": 0.5,
      "adiabatic_temperature_k": 2770.021623247485,
      "oxygen_atom_mole_fraction": 0.0018890214267765124,
      "hydrogen_atom_mole_fraction": 0.07060198350762757,
      "hydroxyl_mole_fraction": 0.019261294512585563,
      "na_o_o_partial_pump_rate_per_na_s": 60.9931260964365
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 0.21,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 1662.5198084081644,
      "oxygen_atom_mole_fraction": 7.802941374871554e-06,
      "hydrogen_atom_mole_fraction": 2.3255874381990948e-07,
      "hydroxyl_mole_fraction": 0.00029213606282523717,
      "na_o_o_partial_pump_rate_per_na_s": 0.02265022585920094
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 0.21,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2118.05047070317,
      "oxygen_atom_mole_fraction": 0.0002828244020708864,
      "hydrogen_atom_mole_fraction": 7.988666900916022e-05,
      "hydroxyl_mole_fraction": 0.003625212394491274,
      "na_o_o_partial_pump_rate_per_na_s": 18.333722434985763
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.21,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2407.9416248924113,
      "oxygen_atom_mole_fraction": 0.0005649260851096531,
      "hydrogen_atom_mole_fraction": 0.0016695284645402095,
      "hydroxyl_mole_fraction": 0.007136247025058766,
      "na_o_o_partial_pump_rate_per_na_s": 56.595363616408626
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 0.21,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2366.615785505684,
      "oxygen_atom_mole_fraction": 6.258287629504513e-05,
      "hydrogen_atom_mole_fraction": 0.0032479530867380872,
      "hydroxyl_mole_fraction": 0.002272386022197647,
      "na_o_o_partial_pump_rate_per_na_s": 0.7190267218856596
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 0.21,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2263.442989137331,
      "oxygen_atom_mole_fraction": 9.739166951102602e-06,
      "hydrogen_atom_mole_fraction": 0.002604144968307697,
      "hydroxyl_mole_fraction": 0.0007988036562642983,
      "na_o_o_partial_pump_rate_per_na_s": 0.019036802626878287
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 0.21,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2076.9626189805504,
      "oxygen_atom_mole_fraction": 4.325353259590623e-07,
      "hydrogen_atom_mole_fraction": 0.001164055676627552,
      "hydroxyl_mole_fraction": 0.0001332952814281811,
      "na_o_o_partial_pump_rate_per_na_s": 4.459388518612678e-05
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 0.38,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2312.823910975358,
      "oxygen_atom_mole_fraction": 0.001795467037125099,
      "hydrogen_atom_mole_fraction": 0.0003400540933850722,
      "hydroxyl_mole_fraction": 0.01158100929294316,
      "na_o_o_partial_pump_rate_per_na_s": 619.6682453924435
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 0.38,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2678.794292987293,
      "oxygen_atom_mole_fraction": 0.00741157110917142,
      "hydrogen_atom_mole_fraction": 0.005818466060810277,
      "hydroxyl_mole_fraction": 0.033892347657877075,
      "na_o_o_partial_pump_rate_per_na_s": 7871.025790416848
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.38,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2815.9422926774846,
      "oxygen_atom_mole_fraction": 0.00711999652140268,
      "hydrogen_atom_mole_fraction": 0.017879677284110156,
      "hydroxyl_mole_fraction": 0.037439395060015146,
      "na_o_o_partial_pump_rate_per_na_s": 6573.5741758053055
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 0.38,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2811.708228038255,
      "oxygen_atom_mole_fraction": 0.0031552778321733256,
      "hydrogen_atom_mole_fraction": 0.025983652652367982,
      "hydroxyl_mole_fraction": 0.024819491345657967,
      "na_o_o_partial_pump_rate_per_na_s": 1294.8641735989909
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 0.38,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2730.7213559370057,
      "oxygen_atom_mole_fraction": 0.0009634865886875624,
      "hydrogen_atom_mole_fraction": 0.02474860311760165,
      "hydroxyl_mole_fraction": 0.012769771056752248,
      "na_o_o_partial_pump_rate_per_na_s": 128.0047483372735
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 0.38,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2515.3861074488855,
      "oxygen_atom_mole_fraction": 7.281865019966195e-05,
      "hydrogen_atom_mole_fraction": 0.013488439910300421,
      "hydroxyl_mole_fraction": 0.0028575525506350555,
      "na_o_o_partial_pump_rate_per_na_s": 0.8617185437479434
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 0.6,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2697.4132448074383,
      "oxygen_atom_mole_fraction": 0.013980199678988491,
      "hydrogen_atom_mole_fraction": 0.005015891604753214,
      "hydroxyl_mole_fraction": 0.04794944741201057,
      "na_o_o_partial_pump_rate_per_na_s": 27619.847966131656
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 0.6,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2920.6544888279545,
      "oxygen_atom_mole_fraction": 0.022421233220720472,
      "hydrogen_atom_mole_fraction": 0.022333702497203612,
      "hydroxyl_mole_fraction": 0.07392038992620761,
      "na_o_o_partial_pump_rate_per_na_s": 60596.58250941489
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.6,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2995.3032254292175,
      "oxygen_atom_mole_fraction": 0.017768677548053044,
      "hydrogen_atom_mole_fraction": 0.04231905139078196,
      "hydroxyl_mole_fraction": 0.06990662545408374,
      "na_o_o_partial_pump_rate_per_na_s": 36184.12958611005
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 0.6,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2985.302761607377,
      "oxygen_atom_mole_fraction": 0.009507369494082495,
      "hydrogen_atom_mole_fraction": 0.05388548690597623,
      "hydroxyl_mole_fraction": 0.05060445431513218,
      "na_o_o_partial_pump_rate_per_na_s": 10428.779518718617
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 0.6,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2921.084818035327,
      "oxygen_atom_mole_fraction": 0.003922897892368582,
      "hydrogen_atom_mole_fraction": 0.05323363392880696,
      "hydroxyl_mole_fraction": 0.03074330411757873,
      "na_o_o_partial_pump_rate_per_na_s": 1854.4502177493798
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 0.6,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2724.1847776066465,
      "oxygen_atom_mole_fraction": 0.0004679459171429743,
      "hydrogen_atom_mole_fraction": 0.033813797122735134,
      "hydroxyl_mole_fraction": 0.008885941638424889,
      "na_o_o_partial_pump_rate_per_na_s": 30.33945025032949
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 1.0,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2947.7734317885806,
      "oxygen_atom_mole_fraction": 0.04243148445549071,
      "hydrogen_atom_mole_fraction": 0.020201133386347086,
      "hydroxyl_mole_fraction": 0.10668316958247567,
      "na_o_o_partial_pump_rate_per_na_s": 213048.1448885511
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 1.0,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 3083.8618430394927,
      "oxygen_atom_mole_fraction": 0.04489395989001482,
      "hydrogen_atom_mole_fraction": 0.04946978337291825,
      "hydroxyl_mole_fraction": 0.12275389493711356,
      "na_o_o_partial_pump_rate_per_na_s": 217909.17053566742
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 1.0,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 3122.1913114758086,
      "oxygen_atom_mole_fraction": 0.032228989305599864,
      "hydrogen_atom_mole_fraction": 0.07435244800209304,
      "hydroxyl_mole_fraction": 0.10671420516066499,
      "na_o_o_partial_pump_rate_per_na_s": 109562.98528258831
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 1.0,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 3102.334436837608,
      "oxygen_atom_mole_fraction": 0.01816800236592589,
      "hydrogen_atom_mole_fraction": 0.08670025979355449,
      "hydroxyl_mole_fraction": 0.07840265866528418,
      "na_o_o_partial_pump_rate_per_na_s": 35263.59899239957
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 1.0,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 3042.5936787694245,
      "oxygen_atom_mole_fraction": 0.008533465327096684,
      "hydrogen_atom_mole_fraction": 0.08503752743223701,
      "hydroxyl_mole_fraction": 0.05091726671279318,
      "na_o_o_partial_pump_rate_per_na_s": 8088.210493538127
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 1.0,
      "pressure_bar": 1.4,
      "adiabatic_temperature_k": 2859.97702070744,
      "oxygen_atom_mole_fraction": 0.0013477396042837443,
      "hydrogen_atom_mole_fraction": 0.05822856594015527,
      "hydroxyl_mole_fraction": 0.017167948244861647,
      "na_o_o_partial_pump_rate_per_na_s": 228.33705734087283
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 0.21,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 1662.8470337019276,
      "oxygen_atom_mole_fraction": 4.633496617867862e-06,
      "hydrogen_atom_mole_fraction": 1.0635985459417214e-07,
      "hydroxyl_mole_fraction": 0.00022525587515107837,
      "na_o_o_partial_pump_rate_per_na_s": 0.06517282071624238
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 0.21,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2123.855879266286,
      "oxygen_atom_mole_fraction": 0.0001743097061826332,
      "hydrogen_atom_mole_fraction": 3.843174811942035e-05,
      "hydroxyl_mole_fraction": 0.0028656693458604257,
      "na_o_o_partial_pump_rate_per_na_s": 56.53878519786814
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.21,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2437.8119888547735,
      "oxygen_atom_mole_fraction": 0.00034575822075088507,
      "hydrogen_atom_mole_fraction": 0.0010106721049304506,
      "hydroxyl_mole_fraction": 0.005743610118058033,
      "na_o_o_partial_pump_rate_per_na_s": 168.84881990956876
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 0.21,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2379.892636964953,
      "oxygen_atom_mole_fraction": 2.5361430773425408e-05,
      "hydrogen_atom_mole_fraction": 0.002051483247918541,
      "hydroxyl_mole_fraction": 0.0014638361780045296,
      "na_o_o_partial_pump_rate_per_na_s": 0.953204728662034
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 0.21,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2271.1969685317385,
      "oxygen_atom_mole_fraction": 3.732940670031224e-06,
      "hydrogen_atom_mole_fraction": 0.0016079853047313631,
      "hydroxyl_mole_fraction": 0.0004980954291729677,
      "na_o_o_partial_pump_rate_per_na_s": 0.02267493196020939
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 0.21,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2079.9802802010795,
      "oxygen_atom_mole_fraction": 1.5788032327159758e-07,
      "hydrogen_atom_mole_fraction": 0.0007023042776596444,
      "hydroxyl_mole_fraction": 8.078755960116669e-05,
      "na_o_o_partial_pump_rate_per_na_s": 4.836052380582106e-05
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 0.38,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2329.2005635990386,
      "oxygen_atom_mole_fraction": 0.0011690804389343325,
      "hydrogen_atom_mole_fraction": 0.00017648011874390606,
      "hydroxyl_mole_fraction": 0.009494802016762232,
      "na_o_o_partial_pump_rate_per_na_s": 2114.600994832048
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 0.38,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2739.0759809887563,
      "oxygen_atom_mole_fraction": 0.005633186732375705,
      "hydrogen_atom_mole_fraction": 0.0038058274871092678,
      "hydroxyl_mole_fraction": 0.030881532512408653,
      "na_o_o_partial_pump_rate_per_na_s": 35502.05999569075
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.38,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2904.620938483346,
      "oxygen_atom_mole_fraction": 0.0055201768560203925,
      "hydrogen_atom_mole_fraction": 0.013556845342513371,
      "hydroxyl_mole_fraction": 0.03496597896502873,
      "na_o_o_partial_pump_rate_per_na_s": 30316.598606682077
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 0.38,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2892.8048132309273,
      "oxygen_atom_mole_fraction": 0.002108255080117751,
      "hydrogen_atom_mole_fraction": 0.020111923399057232,
      "hydroxyl_mole_fraction": 0.02137889416472064,
      "na_o_o_partial_pump_rate_per_na_s": 4458.219688850187
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 0.38,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2791.275950162027,
      "oxygen_atom_mole_fraction": 0.0005511163303580127,
      "hydrogen_atom_mole_fraction": 0.018311517591306954,
      "hydroxyl_mole_fraction": 0.01004894059537908,
      "na_o_o_partial_pump_rate_per_na_s": 327.21592353653205
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 0.38,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2545.530421998639,
      "oxygen_atom_mole_fraction": 3.390583552964517e-05,
      "hydrogen_atom_mole_fraction": 0.009117020374379664,
      "hydroxyl_mole_fraction": 0.0019933826132883265,
      "na_o_o_partial_pump_rate_per_na_s": 1.489174997026878
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 0.6,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2759.5962107949013,
      "oxygen_atom_mole_fraction": 0.01075435820017979,
      "hydrogen_atom_mole_fraction": 0.0032833016819746323,
      "hydroxyl_mole_fraction": 0.04391839475819289,
      "na_o_o_partial_pump_rate_per_na_s": 127476.85272826227
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 0.6,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 3024.1910397973056,
      "oxygen_atom_mole_fraction": 0.01893621657681477,
      "hydrogen_atom_mole_fraction": 0.01708323028136895,
      "hydroxyl_mole_fraction": 0.07228186918142752,
      "na_o_o_partial_pump_rate_per_na_s": 329095.08543259435
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.6,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 3115.6148335142593,
      "oxygen_atom_mole_fraction": 0.014973523376108223,
      "hydrogen_atom_mole_fraction": 0.03477064615093911,
      "hydroxyl_mole_fraction": 0.06872046881925155,
      "na_o_o_partial_pump_rate_per_na_s": 193871.46918240996
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 0.6,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 3101.107539065419,
      "oxygen_atom_mole_fraction": 0.007436877392507476,
      "hydrogen_atom_mole_fraction": 0.044855090141815004,
      "hydroxyl_mole_fraction": 0.04776867964551107,
      "na_o_o_partial_pump_rate_per_na_s": 48272.63512641593
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 0.6,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 3020.098258886561,
      "oxygen_atom_mole_fraction": 0.002760812167087938,
      "hydrogen_atom_mole_fraction": 0.04317891399685672,
      "hydroxyl_mole_fraction": 0.027291526766542208,
      "na_o_o_partial_pump_rate_per_na_s": 7014.31058336594
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 0.6,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2785.8032705116507,
      "oxygen_atom_mole_fraction": 0.00026855017243646804,
      "hydrogen_atom_mole_fraction": 0.02518745290606579,
      "hydroxyl_mole_fraction": 0.006996731496309355,
      "na_o_o_partial_pump_rate_per_na_s": 78.00158013998065
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 1.0,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 3054.1017329193614,
      "oxygen_atom_mole_fraction": 0.03635225543593209,
      "hydrogen_atom_mole_fraction": 0.015393122124194731,
      "hydroxyl_mole_fraction": 0.10489286059023599,
      "na_o_o_partial_pump_rate_per_na_s": 1189184.229614213
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 1.0,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 3217.807116836567,
      "oxygen_atom_mole_fraction": 0.040047867613998527,
      "hydrogen_atom_mole_fraction": 0.040924628752180926,
      "hydroxyl_mole_fraction": 0.12436883473262117,
      "na_o_o_partial_pump_rate_per_na_s": 1300146.2114037406
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 1.0,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 3265.3634175876427,
      "oxygen_atom_mole_fraction": 0.0284454646511897,
      "hydrogen_atom_mole_fraction": 0.0639046513246259,
      "hydroxyl_mole_fraction": 0.10786262932731873,
      "na_o_o_partial_pump_rate_per_na_s": 636966.2709777176
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 1.0,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 3240.6898676112537,
      "oxygen_atom_mole_fraction": 0.015263499896875053,
      "hydrogen_atom_mole_fraction": 0.0750246809478024,
      "hydroxyl_mole_fraction": 0.07712955050176229,
      "na_o_o_partial_pump_rate_per_na_s": 186203.0245026224
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 1.0,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 3166.8162420840267,
      "oxygen_atom_mole_fraction": 0.006662085399502977,
      "hydrogen_atom_mole_fraction": 0.07234869771051768,
      "hydroxyl_mole_fraction": 0.047999046659174247,
      "na_o_o_partial_pump_rate_per_na_s": 37147.37080091824
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 1.0,
      "pressure_bar": 4.0,
      "adiabatic_temperature_k": 2947.3875071035345,
      "oxygen_atom_mole_fraction": 0.0008884335435930889,
      "hydrogen_atom_mole_fraction": 0.04625619264705732,
      "hydroxyl_mole_fraction": 0.014648865535505094,
      "na_o_o_partial_pump_rate_per_na_s": 762.6562528059126
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 0.21,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 1663.0165333283824,
      "oxygen_atom_mole_fraction": 3.2827012743457026e-06,
      "hydrogen_atom_mole_fraction": 6.340760649260017e-08,
      "hydroxyl_mole_fraction": 0.00018965974447287794,
      "na_o_o_partial_pump_rate_per_na_s": 0.13082266813235002
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 0.21,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2126.7493712489704,
      "oxygen_atom_mole_fraction": 0.00012580794549417682,
      "hydrogen_atom_mole_fraction": 2.3489653636141355e-05,
      "hydroxyl_mole_fraction": 0.0024429082491795274,
      "na_o_o_partial_pump_rate_per_na_s": 117.48892302158146
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.21,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2454.4392302495808,
      "oxygen_atom_mole_fraction": 0.00024416325184301203,
      "hydrogen_atom_mole_fraction": 0.0007094682606619107,
      "hydroxyl_mole_fraction": 0.0049026658263014574,
      "na_o_o_partial_pump_rate_per_na_s": 332.2534060837899
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 0.21,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2385.965186943076,
      "oxygen_atom_mole_fraction": 1.3549368104386638e-05,
      "hydrogen_atom_mole_fraction": 0.0014945148130210693,
      "hydroxyl_mole_fraction": 0.001075723232496381,
      "na_o_o_partial_pump_rate_per_na_s": 1.0827377694333293
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 0.21,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2274.680576969017,
      "oxygen_atom_mole_fraction": 1.9438216443256686e-06,
      "hydrogen_atom_mole_fraction": 0.001158987932893331,
      "hydroxyl_mole_fraction": 0.00036058272072956086,
      "na_o_o_partial_pump_rate_per_na_s": 0.02451802013727709
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 0.21,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2081.2964264216953,
      "oxygen_atom_mole_fraction": 8.039631796071072e-08,
      "hydrogen_atom_mole_fraction": 0.0005008616387608988,
      "hydroxyl_mole_fraction": 5.772949669727568e-05,
      "na_o_o_partial_pump_rate_per_na_s": 5.009770715753688e-05
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 0.38,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2337.8260194294317,
      "oxygen_atom_mole_fraction": 0.0008691150045019504,
      "hydrogen_atom_mole_fraction": 0.00011237690554730253,
      "hydroxyl_mole_fraction": 0.008255148856267805,
      "na_o_o_partial_pump_rate_per_na_s": 4640.272959159482
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 0.38,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2774.850864557851,
      "oxygen_atom_mole_fraction": 0.004601991714937662,
      "hydrogen_atom_mole_fraction": 0.002785885528363245,
      "hydroxyl_mole_fraction": 0.02863547667151504,
      "na_o_o_partial_pump_rate_per_na_s": 92347.63548718717
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.38,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2961.4957382241723,
      "oxygen_atom_mole_fraction": 0.0045651697790162205,
      "hydrogen_atom_mole_fraction": 0.011061435840176844,
      "hydroxyl_mole_fraction": 0.03298150254046155,
      "na_o_o_partial_pump_rate_per_na_s": 79782.02438159958
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 0.38,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2942.3425653969643,
      "oxygen_atom_mole_fraction": 0.0015405221125967463,
      "hydrogen_atom_mole_fraction": 0.01663051473585254,
      "hydroxyl_mole_fraction": 0.018849576252650255,
      "na_o_o_partial_pump_rate_per_na_s": 9203.707600669495
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 0.38,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2825.704918693076,
      "oxygen_atom_mole_fraction": 0.00036098810244804475,
      "hydrogen_atom_mole_fraction": 0.014644285563418265,
      "hydroxyl_mole_fraction": 0.008313435140372149,
      "na_o_o_partial_pump_rate_per_na_s": 547.9558533772388
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 0.38,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2560.8643357070337,
      "oxygen_atom_mole_fraction": 1.9552432503357657e-05,
      "hydrogen_atom_mole_fraction": 0.006890728845169536,
      "hydroxyl_mole_fraction": 0.0015305701793825912,
      "na_o_o_partial_pump_rate_per_na_s": 1.9572299621146994
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 0.6,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2796.9958364437084,
      "oxygen_atom_mole_fraction": 0.008860137003787924,
      "hydrogen_atom_mole_fraction": 0.0024110500279029673,
      "hydroxyl_mole_fraction": 0.04089005744563371,
      "na_o_o_partial_pump_rate_per_na_s": 336907.472552213
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 0.6,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 3091.5924809353332,
      "oxygen_atom_mole_fraction": 0.016675209232343946,
      "hydrogen_atom_mole_fraction": 0.013990500949639096,
      "hydroxyl_mole_fraction": 0.07051241716455278,
      "na_o_o_partial_pump_rate_per_na_s": 976768.1901392203
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.6,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 3196.2681590579846,
      "oxygen_atom_mole_fraction": 0.013158891910643084,
      "hydrogen_atom_mole_fraction": 0.03008054457880469,
      "hydroxyl_mole_fraction": 0.06731208105273719,
      "na_o_o_partial_pump_rate_per_na_s": 569069.9209750756
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 0.6,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 3177.4956489740875,
      "oxygen_atom_mole_fraction": 0.006145728002262591,
      "hydrogen_atom_mole_fraction": 0.039158117318944946,
      "hydroxyl_mole_fraction": 0.045246521793277726,
      "na_o_o_partial_pump_rate_per_na_s": 125600.14773168326
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 0.6,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 3082.7462540124097,
      "oxygen_atom_mole_fraction": 0.0021009208795745365,
      "hydrogen_atom_mole_fraction": 0.036897092494420934,
      "hydroxyl_mole_fraction": 0.024639756201158217,
      "na_o_o_partial_pump_rate_per_na_s": 15593.989796356216
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 0.6,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 2821.1520430547666,
      "oxygen_atom_mole_fraction": 0.00017663049486018025,
      "hydrogen_atom_mole_fraction": 0.020237720463070534,
      "hydroxyl_mole_fraction": 0.005797866881600818,
      "na_o_o_partial_pump_rate_per_na_s": 131.6108805268556
    },
    {
      "phi": 0.5,
      "oxygen_fraction": 1.0,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 3123.6560033781175,
      "oxygen_atom_mole_fraction": 0.032331954776084644,
      "hydrogen_atom_mole_fraction": 0.01258906329815212,
      "hydroxyl_mole_fraction": 0.10273706115359897,
      "na_o_o_partial_pump_rate_per_na_s": 3597086.924251009
    },
    {
      "phi": 0.75,
      "oxygen_fraction": 1.0,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 3308.6142815379926,
      "oxygen_atom_mole_fraction": 0.03672045044988676,
      "hydrogen_atom_mole_fraction": 0.03554466287505778,
      "hydroxyl_mole_fraction": 0.12459829834015203,
      "na_o_o_partial_pump_rate_per_na_s": 4135586.687814903
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 1.0,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 3363.6187286937243,
      "oxygen_atom_mole_fraction": 0.025869601163734695,
      "hydrogen_atom_mole_fraction": 0.05715813654825802,
      "hydroxyl_mole_fraction": 0.10788012208837039,
      "na_o_o_partial_pump_rate_per_na_s": 1986000.4886815825
    },
    {
      "phi": 1.25,
      "oxygen_fraction": 1.0,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 3334.771511397079,
      "oxygen_atom_mole_fraction": 0.013339539547822339,
      "hydrogen_atom_mole_fraction": 0.06742575472512972,
      "hydroxyl_mole_fraction": 0.07547454776155575,
      "na_o_o_partial_pump_rate_per_na_s": 537233.29606864
    },
    {
      "phi": 1.5,
      "oxygen_fraction": 1.0,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 3249.181465954647,
      "oxygen_atom_mole_fraction": 0.005492930402658018,
      "hydrogen_atom_mole_fraction": 0.06411078060819432,
      "hydroxyl_mole_fraction": 0.04540392424474808,
      "na_o_o_partial_pump_rate_per_na_s": 95956.33829821783
    },
    {
      "phi": 2.0,
      "oxygen_fraction": 1.0,
      "pressure_bar": 8.0,
      "adiabatic_temperature_k": 3001.2352990119552,
      "oxygen_atom_mole_fraction": 0.000644522784154817,
      "hydrogen_atom_mole_fraction": 0.03889651157102974,
      "hydroxyl_mole_fraction": 0.012849961379097023,
      "na_o_o_partial_pump_rate_per_na_s": 1548.4238998664728
    }
  ],
  "flame_speed": [
    {
      "phi": 0.7,
      "oxygen_fraction": 0.21,
      "pressure_bar": 0.5,
      "laminar_flame_speed_m_s": 1.3501425933846394,
      "maximum_temperature_k": 1978.8124158303383
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.21,
      "pressure_bar": 0.5,
      "laminar_flame_speed_m_s": 2.2938838418929803,
      "maximum_temperature_k": 2355.1748387991647
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 0.21,
      "pressure_bar": 0.5,
      "laminar_flame_speed_m_s": 2.8179115380265802,
      "maximum_temperature_k": 2329.4082844687714
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 0.38,
      "pressure_bar": 0.5,
      "laminar_flame_speed_m_s": 3.5244275116678625,
      "maximum_temperature_k": 2549.2910080894494
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.38,
      "pressure_bar": 0.5,
      "laminar_flame_speed_m_s": 4.580344572942526,
      "maximum_temperature_k": 2719.1390780637594
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 0.38,
      "pressure_bar": 0.5,
      "laminar_flame_speed_m_s": 5.051994409906601,
      "maximum_temperature_k": 2717.91664978576
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 0.6,
      "pressure_bar": 0.5,
      "laminar_flame_speed_m_s": 5.737139590600112,
      "maximum_temperature_k": 2785.7944192984082
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.6,
      "pressure_bar": 0.5,
      "laminar_flame_speed_m_s": 6.722276420312619,
      "maximum_temperature_k": 2878.1679344149793
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 0.6,
      "pressure_bar": 0.5,
      "laminar_flame_speed_m_s": 7.028892944785574,
      "maximum_temperature_k": 2868.4358899318013
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 1.0,
      "pressure_bar": 0.5,
      "laminar_flame_speed_m_s": 8.57202850775805,
      "maximum_temperature_k": 2937.686047479552
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 1.0,
      "pressure_bar": 0.5,
      "laminar_flame_speed_m_s": 9.237361992504942,
      "maximum_temperature_k": 2987.1494318685254
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 1.0,
      "pressure_bar": 0.5,
      "laminar_flame_speed_m_s": 9.172584345761821,
      "maximum_temperature_k": 2965.0109998310386
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 0.21,
      "pressure_bar": 1.4,
      "laminar_flame_speed_m_s": 1.1103186892496673,
      "maximum_temperature_k": 1961.9512169403984
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.21,
      "pressure_bar": 1.4,
      "laminar_flame_speed_m_s": 2.3069919505903607,
      "maximum_temperature_k": 2379.762660177856
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 0.21,
      "pressure_bar": 1.4,
      "laminar_flame_speed_m_s": 2.99373673479839,
      "maximum_temperature_k": 2356.1242611660914
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 0.38,
      "pressure_bar": 1.4,
      "laminar_flame_speed_m_s": 3.6879012799570448,
      "maximum_temperature_k": 2593.931872351434
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.38,
      "pressure_bar": 1.4,
      "laminar_flame_speed_m_s": 5.102411854926668,
      "maximum_temperature_k": 2806.611144013328
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 0.38,
      "pressure_bar": 1.4,
      "laminar_flame_speed_m_s": 5.765805991742472,
      "maximum_temperature_k": 2803.196644999877
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 0.6,
      "pressure_bar": 1.4,
      "laminar_flame_speed_m_s": 6.34812567688091,
      "maximum_temperature_k": 2874.9863490723365
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.6,
      "pressure_bar": 1.4,
      "laminar_flame_speed_m_s": 7.710765855591386,
      "maximum_temperature_k": 2989.3779403593717
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 0.6,
      "pressure_bar": 1.4,
      "laminar_flame_speed_m_s": 8.171464164653104,
      "maximum_temperature_k": 2977.723959002877
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 1.0,
      "pressure_bar": 1.4,
      "laminar_flame_speed_m_s": 9.821447884618367,
      "maximum_temperature_k": 3057.762012073436
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 1.0,
      "pressure_bar": 1.4,
      "laminar_flame_speed_m_s": 10.829973661935146,
      "maximum_temperature_k": 3118.648662243024
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 1.0,
      "pressure_bar": 1.4,
      "laminar_flame_speed_m_s": 10.839882361404225,
      "maximum_temperature_k": 3093.6655858162476
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 0.21,
      "pressure_bar": 4.0,
      "laminar_flame_speed_m_s": 0.7730454691226081,
      "maximum_temperature_k": 1964.4844968758962
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.21,
      "pressure_bar": 4.0,
      "laminar_flame_speed_m_s": 2.0044232739217076,
      "maximum_temperature_k": 2394.788929895377
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 0.21,
      "pressure_bar": 4.0,
      "laminar_flame_speed_m_s": 2.8586760105334243,
      "maximum_temperature_k": 2371.728249299903
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 0.38,
      "pressure_bar": 4.0,
      "laminar_flame_speed_m_s": 3.386769552967018,
      "maximum_temperature_k": 2630.7299127256024
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.38,
      "pressure_bar": 4.0,
      "laminar_flame_speed_m_s": 5.258013770663486,
      "maximum_temperature_k": 2891.284799727048
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 0.38,
      "pressure_bar": 4.0,
      "laminar_flame_speed_m_s": 6.124110252603478,
      "maximum_temperature_k": 2885.40739120964
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 0.6,
      "pressure_bar": 4.0,
      "laminar_flame_speed_m_s": 6.582707821264074,
      "maximum_temperature_k": 2966.599121440801
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.6,
      "pressure_bar": 4.0,
      "laminar_flame_speed_m_s": 8.409213078421862,
      "maximum_temperature_k": 3108.13919953576
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 0.6,
      "pressure_bar": 4.0,
      "laminar_flame_speed_m_s": 9.04223216800826,
      "maximum_temperature_k": 3092.9414481719555
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 1.0,
      "pressure_bar": 4.0,
      "laminar_flame_speed_m_s": 10.74762773776598,
      "maximum_temperature_k": 3182.5834805983955
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 1.0,
      "pressure_bar": 4.0,
      "laminar_flame_speed_m_s": 12.155442004600818,
      "maximum_temperature_k": 3260.6348758449594
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 1.0,
      "pressure_bar": 4.0,
      "laminar_flame_speed_m_s": 12.23198706215872,
      "maximum_temperature_k": 3232.6019689951295
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 0.21,
      "pressure_bar": 8.0,
      "laminar_flame_speed_m_s": 0.4614684978802589,
      "maximum_temperature_k": 1938.634111149929
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.21,
      "pressure_bar": 8.0,
      "laminar_flame_speed_m_s": 1.6066702279322043,
      "maximum_temperature_k": 2398.3348830393
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 0.21,
      "pressure_bar": 8.0,
      "laminar_flame_speed_m_s": 2.551736860601844,
      "maximum_temperature_k": 2382.8276424822247
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 0.38,
      "pressure_bar": 8.0,
      "laminar_flame_speed_m_s": 2.9219320452247306,
      "maximum_temperature_k": 2644.8211597948693
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.38,
      "pressure_bar": 8.0,
      "laminar_flame_speed_m_s": 4.972982759774689,
      "maximum_temperature_k": 2941.3071673014124
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 0.38,
      "pressure_bar": 8.0,
      "laminar_flame_speed_m_s": 6.020242422430052,
      "maximum_temperature_k": 2937.8017147010614
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 0.6,
      "pressure_bar": 8.0,
      "laminar_flame_speed_m_s": 6.2954212584917135,
      "maximum_temperature_k": 3020.947770014675
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 0.6,
      "pressure_bar": 8.0,
      "laminar_flame_speed_m_s": 8.445487729795612,
      "maximum_temperature_k": 3188.793862780701
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 0.6,
      "pressure_bar": 8.0,
      "laminar_flame_speed_m_s": 9.192023396370894,
      "maximum_temperature_k": 3171.693595052188
    },
    {
      "phi": 0.7,
      "oxygen_fraction": 1.0,
      "pressure_bar": 8.0,
      "laminar_flame_speed_m_s": 10.829339234453016,
      "maximum_temperature_k": 3265.300040347397
    },
    {
      "phi": 1.0,
      "oxygen_fraction": 1.0,
      "pressure_bar": 8.0,
      "laminar_flame_speed_m_s": 12.591229740679504,
      "maximum_temperature_k": 3359.573096128981
    },
    {
      "phi": 1.3,
      "oxygen_fraction": 1.0,
      "pressure_bar": 8.0,
      "laminar_flame_speed_m_s": 12.833987587073606,
      "maximum_temperature_k": 3330.773921998912
    }
  ]
});
